# Generated by Django 4.1 on 2023-02-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
