# Generated by Django 4.0.6 on 2023-04-25 17:33

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0005_profile_blogmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='default.png', null=True, upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.DeleteModel(
            name='BlogModel',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
